services: docker
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
before_script:
  - TRAVIS_TAG=v7.1.5
  # Extract the version components out of a `v12.34.56` or `12.34.56` version string (only works if this is a
  - IFS=. read MAJOR MINOR PATCH <<< "${TRAVIS_TAG}"
  - docker -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - docker build -t "bkuhl/php:latest" .
  - docker images
  - ~/official-images/test/run.sh "bkuhl/php:latest"
before_deploy:
  # Extract the version components out of a `v12.34.56` or `12.34.56` version string (only works if this is a
  - IFS=. read MAJOR MINOR PATCH <<< "${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "bkuhl/php:latest" && docker tag "bkuhl/php:latest" "bkuhl:${MAJOR}" && docker push "bkuhl:${MAJOR}" && docker tag "bkuhl/php:latest" "bkuhl:${MAJOR}.${MINOR}" && docker push "bkuhl:${MAJOR}.${MINOR}" && docker tag "bkuhl/php:latest" "bkuhl:${MAJOR}.${MINOR}.${PATCH}" && docker push "bkuhl:${MAJOR}.${PATCH}"
#  skip_cleanup: false
#  on:
#    tags: true